name: network
description: "Helper Dto, endpoint, provider"
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.19.0
  dio: ^5.7.0
  equatable: ^2.0.7
  pretty_dio_logger: 1.3.1
  freezed_annotation: ^3.0.0
  freezed: ^3.0.3

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  very_good_analysis: 5.1.0
  injectable_generator: ^2.7.0
flutter: